pointcloud_channel_fusions:
  rgb: 'color'
  default: 'average'

image_channel_fusions:
  rgb: 'color'
  default: 'exponential'
  feat_.*: 'exponential'

subscribers:
  front_cam:
    topic_name: '/cloud_registered_body'
    data_type: pointcloud
  back_cam:
    topic_name: '/cloud_registered_body_back_filtered'
    data_type: pointcloud
  color_cam:
    topic_name: '/c1_camera/image_raw'
    camera_info_topic_name: '/c1_camera/camera_info'
    data_type: image

publishers:
  elevation_map_raw:
    layers: ['elevation', 'rgb']
    basic_layers: ['elevation']
    fps: 5.0
  elevation_map_filter:
    layers: ['min_filter', 'rgb']
    basic_layers: ['min_filter']
    fps: 3.0
