# RobStride CAN Hardware Node Configuration
robstride_can_hardware:
  ros__parameters:
    rate_hz: 200
    rt_priority: 80
    default_coxa_kp: 28.0
    default_coxa_kd: 0.7
    default_kp: 28.0
    default_kd: 0.7

jaguar_can_hardware:
  ros__parameters:
    rate_hz: 200
    default_coxa_kp: 28.0
    default_coxa_kd: 0.7
    default_kp: 28.0
    default_kd: 0.7
